# Generated by Django 2.2.3 on 2019-08-07 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0003_auto_20190210_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoAbono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPrestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Interes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.FloatField()),
                ('descripcion', models.TextField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='PlanFinanciero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(default=django.utils.timezone.now)),
                ('capital_prestado', models.FloatField()),
                ('meses_plazo', models.IntegerField(verbose_name='Tiempo plazo')),
                ('valor_interes', models.FloatField(null=True)),
                ('saldo_capital', models.FloatField(null=True)),
                ('saldo_interes', models.FloatField(null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True, max_length=150)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
                ('estado', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='prestamos.EstadoPrestamo')),
                ('porcentaje_aplicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.Interes')),
                ('prestamo_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prestamos.Prestamo')),
            ],
        ),
        migrations.CreateModel(
            name='TiposPrestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UnionCuentas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_union', models.DateField(default=django.utils.timezone.now)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('capital_total', models.FloatField()),
                ('valor_abono_capital_total', models.FloatField()),
                ('valor_abono_interes_total', models.FloatField()),
                ('saldo', models.FloatField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnionCuentasDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.Prestamo')),
                ('union_cuentas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.UnionCuentas')),
            ],
        ),
        migrations.AddField(
            model_name='prestamo',
            name='tipo_prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.TiposPrestamo'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PlanFinancieroDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_abono', models.DateField(default=django.utils.timezone.now)),
                ('valor_capital', models.FloatField()),
                ('valor_interes', models.FloatField()),
                ('concepto', models.CharField(max_length=80)),
                ('plan_financiero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.PlanFinanciero')),
            ],
        ),
        migrations.AddField(
            model_name='planfinanciero',
            name='prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.Prestamo'),
        ),
        migrations.AddField(
            model_name='planfinanciero',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_descuento', models.DateField(default=django.utils.timezone.now)),
                ('valor_descuento', models.FloatField(default=0)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('descontadopor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.Prestamo')),
            ],
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_abono', models.DateField(default=django.utils.timezone.now)),
                ('valor_abono_capital', models.FloatField()),
                ('valor_abono_interes', models.FloatField()),
                ('observaciones', models.TextField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prestamos.EstadoAbono')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.Prestamo')),
                ('usuario', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
