# Generated by Django 2.2.8 on 2020-01-17 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abono',
            old_name='usuario',
            new_name='cobrador',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='usuario',
            new_name='cobrador',
        ),
        migrations.RemoveField(
            model_name='planfinanciero',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='unioncuentas',
            name='usuario',
        ),
    ]
