# Generated by Django 2.0.1 on 2018-12-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pic_folder/')),
                ('cedula', models.CharField(blank=True, max_length=30, null=True)),
                ('nombres', models.CharField(max_length=70)),
                ('apellidos', models.CharField(max_length=70)),
                ('direccion', models.CharField(blank=True, max_length=70, null=True)),
                ('telefono_fijo', models.CharField(blank=True, max_length=20, null=True)),
                ('telfono_celular', models.CharField(blank=True, max_length=20, null=True)),
                ('contrasena_cuenta', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
