# Generated by Django 2.0.1 on 2018-12-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='telfono_celular',
            new_name='telefono_celular',
        ),
    ]
